### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by cdeboever3** [Cadair/jupyter_environment_kernels#10]
I've installed using `pip install environment_kernels` and added 
```
c.NotebookApp.kernel_spec_manager_class = 'environment_kernels.EnvironmentKernelSpecManager'
c.EnvironmentKernelSpecManager.env_dirs=['~/software/anaconda/envs']
```
to my Jupyter config file. My anaconda installation is at ~/software/anaconda so I updated that line. I don't see the envs available as kernels when I run the notebook server and I get the following error printing out from the server log
```
[E 08:49:16.162 NotebookApp] Failed to load kernel spec: 'cpb-dev'
    Traceback (most recent call last):
      File "/frazer01/home/cdeboever/software/anaconda/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 59, in get
        d = kernelspec_model(self, kernel_name)
      File "/frazer01/home/cdeboever/software/anaconda/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 22, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "/frazer01/home/cdeboever/software/anaconda/lib/python2.7/site-packages/environment_kernels/core.py", line 64, in get_kernel_spec
        except (NoSuchKernel, FileNotFoundError):
    NameError: global name 'FileNotFoundError' is not defined
[E 08:49:16.166 NotebookApp] Failed to load kernel spec: 'cie'
    Traceback (most recent call last):
      File "/frazer01/home/cdeboever/software/anaconda/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 59, in get
        d = kernelspec_model(self, kernel_name)
      File "/frazer01/home/cdeboever/software/anaconda/lib/python2.7/site-packages/notebook/services/kernelspecs/handlers.py", line 22, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "/frazer01/home/cdeboever/software/anaconda/lib/python2.7/site-packages/environment_kernels/core.py", line 64, in get_kernel_spec
        except (NoSuchKernel, FileNotFoundError):
    NameError: global name 'FileNotFoundError' is not defined
```
etc. for all of my envs.

**Comment by JanSchulz** [comment]
What version of python are you using? Py 2.7?

Can you try adding this after the imports: 

```
try:
    FileNotFoundError
except NameError:
    #py2
    FileNotFoundError = IOError
```
[from http://stackoverflow.com/questions/21367320/searching-for-equivalent-of-filenotfounderror-in-python-2]

**Comment by cdeboever3** [comment]
```
$ python --version
Python 2.7.10 :: Anaconda 2.4.0 (64-bit)
```

Thanks, I added the change you did in 222a82977377c49d811e887550b497279e8822f5 to master and installed and things seem to be working now.
