### ISSUE TITLE
activate doesn't work on linux

### ISSUE THREAD

**Issue by janschulz** [Cadair/jupyter_environment_kernels#28]
On linux it's `source activate ...` and not `activate ...` as on windows... Interestingly, the kernel still comes up. So yay :-)

```
Mar 25 22:07:55 littlebottom2 jupyter[8154]: [E 22:07:55.969 NotebookApp] Couldn't get environment variables for commands: ['activate', '/home/js/.binaries/miniconda3/envs/dask/']
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     Traceback (most recent call last):
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 61, in source_env_vars_from_command
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         return source_bash(args)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 73, in source_bash
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         return source_foreign(new_args, stdin=stdin)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 184, in source_foreign
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         seterrpostcmd=ns.seterrpostcmd)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 426, in foreign_shell_data
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         universal_newlines=True)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/.binaries/miniconda3/envs/jupyter-notebook/lib/python3.6/subprocess.py", line 336, in check_output
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         **kwargs).stdout
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/.binaries/miniconda3/envs/jupyter-notebook/lib/python3.6/subprocess.py", line 418, in run
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         output=stdout, stderr=stderr)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     subprocess.CalledProcessError: Command '['bash', '-i', '-c', 'set -e\nactivate /home/js/.binaries/miniconda3/envs/dask/\necho __XONSH_ENV_BEG__\nenv\
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     During handling of the above exception, another exception occurred:
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     Traceback (most recent call last):
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/envs_conda.py", line 48, in _get_env_vars_for_conda_env
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         return source_env_vars_from_command(args)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 63, in source_env_vars_from_command
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         return source_zsh(args)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 82, in source_zsh
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         return source_foreign(new_args, stdin=stdin)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 184, in source_foreign
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         seterrpostcmd=ns.seterrpostcmd)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/external/src/environment-kernels/environment_kernels/activate_helper.py", line 426, in foreign_shell_data
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         universal_newlines=True)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/.binaries/miniconda3/envs/jupyter-notebook/lib/python3.6/subprocess.py", line 336, in check_output
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         **kwargs).stdout
Mar 25 22:07:55 littlebottom2 jupyter[8154]:       File "/home/js/.binaries/miniconda3/envs/jupyter-notebook/lib/python3.6/subprocess.py", line 418, in run
Mar 25 22:07:55 littlebottom2 jupyter[8154]:         output=stdout, stderr=stderr)
Mar 25 22:07:55 littlebottom2 jupyter[8154]:     subprocess.CalledProcessError: Command '['zsh', '-i', '-c', 'set -e\nactivate /home/js/.binaries/miniconda3/envs/dask/\necho __XONSH_ENV_BEG__\nenv\n
Mar 25 22:07:55 littlebottom2 jupyter[8154]: [I 22:07:55.977 NotebookApp] Kernel started: 9ac8dcef-a405-4c0c-94ec-2543abc36e5a
```

**Comment by janschulz** [comment]
And there is another one: currently, at least on python 3.6 and 3.6, the env from the kernel spec doesn't get used to startup the kernel. I tracked that down to the point that the `dict.update(LazyProxyDict()` doesn't use the values in the LazyProxyDict to update the dict. And so [`env.update(kernel_spec.env) doesn't do what it seems](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L252)...

https://github.com/ipython/traitlets/issues/386

My current thinking is to replace the whole proxy magic with a subclass of KernelSpec which does the activation/environment loading on the fly when the `.env` property is accessed... That way seems to be a lot less magic...
