### ISSUE TITLE
pip install's version of environment_kernels does not work

### ISSUE THREAD

**Issue by krishnap25** [Cadair/jupyter_environment_kernels#34]
I installed environment kernels with pip. I tried to launch a notebook and it threw and exception (shown below). Upon further investigation, it became clear that line 169 in core.py was different on the github repo and in my installation. It appears that pip installs a possibly outdated version of environment_kernels. Thanks!

line 169 in core.py installed by pip:
new_kernels = env_data.keys() - self._env_data_cache.keys()

Error I got: 
```
Exception in callback <functools.partial object at 0x7fd146f62f18>
    Traceback (most recent call last):
      File "/home/pillutla/software/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
        ret = callback()
      File "/home/pillutla/software/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/pillutla/software/anaconda2/lib/python2.7/site-packages/environment_kernels/core.py", line 151, in _update_env_data
        self._get_env_data(reload=True)
      File "/home/pillutla/software/anaconda2/lib/python2.7/site-packages/environment_kernels/core.py", line 169, in _get_env_data
        new_kernels = env_data.keys() - self._env_data_cache.keys()
    TypeError: unsupported operand type(s) for -: 'list' and 'list'
```

**Comment by Cadair** [comment]
I will try and bake a new release soon.

**Comment by Cadair** [comment]
This is now released on PyPI
